default: &default
  adapter: postgresql
  encoding: unicode
  max_connections: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: lobebot_development
  username: <%= ENV.fetch("POSTGRES_USERNAME", "dev") %>
  password: <%= ENV.fetch("POSTGRES_PASSWORD", "dev") %>
  host: <%= ENV.fetch("POSTGRES_HOST", "localhost") %>
  port: <%= ENV.fetch("POSTGRES_PORT") { 5432 } %>

test:
  <<: *default
  database: lobebot_test
  username: <%= ENV.fetch("POSTGRES_USERNAME", "dev") %>
  password: <%= ENV.fetch("POSTGRES_PASSWORD", "dev") %>
  host: <%= ENV.fetch("POSTGRES_HOST", "localhost") %>
  port: <%= ENV.fetch("POSTGRES_PORT") { 5432 } %>

production:
  primary: &primary_production
    <<: *default
    database: lobebot
    username: <%= ENV.fetch("POSTGRES_USERNAME", "dev") %>
    password: <%= ENV.fetch("POSTGRES_PASSWORD", "dev") %>
    host: <%= ENV.fetch("POSTGRES_HOST", "localhost") %>
    port: <%= ENV.fetch("POSTGRES_PORT") { 5432 } %>
  cache:
    <<: *primary_production
    database: lobebot_cache
    migrations_paths: db/cache_migrate
  queue:
    <<: *primary_production
    database: lobebot_queue
    migrations_paths: db/queue_migrate
  cable:
    <<: *primary_production
    database: lobebot_cable
    migrations_paths: db/cable_migrate
